try {
    console.log(a)
    let a = 3
} catch (err) {
     alert('let перед использованием нужно объявить')
 }

let a = 1
let b = 0
try {
    if (b === 0) {
        throw 'на ноль делить нельзя'
    }
} catch (error) {
    alert(error)
}
